# Fragmento relevante del Makefile de kernel/
# Agrega la nueva unidad junto a los demas objetos del directorio.

obj-y += fork.o
obj-y += exec_domain.o
obj-y += panic.o
obj-y += signal.o
obj-y += get_process_info.o
obj-y += exit.o
